name: "Deploy to Nuget"

on: 
  push:
    branches: [ master ]

jobs:

  deploy:
  
    name: "Deploy"
    runs-on: "windows-latest"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
                 
    - name: Install Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "4.8.x"
        
     
