name: "Deploy to Nuget"

on: ["push"]

env:
  PROJECT_PATH: "NugetFeedTest/HelloWorld/HelloWorld.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}
  NUGET_SOURCE_URL: "https://nuget.pkg.github.com/RaviPrasadOrg/index.json"

jobs:
  build:
    name: "Deploy"
    runs-on: "windows-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "5.0.x"
        
    - name: Restore package
      run: dotnet restore ${{ env.PROJECT_PATH }}
      
    - name: Build project
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: Pack project
      run: dotnet pack --no-build -c Release ${{ env.PROJECT_PATH }} -o .
      
    - name: Push package
      run: dotnet nuget push *.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ env.NUGET_SOURCE_URL }} 
