name: CI Nuget Feed

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup MS Build
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v3.5.0
        
    - name: Restore NuGet packages
      run: nuget restore NugetFeed/NugetFeed.sln
        
    - name: Build Solution
      run: msbuild NugetFeed/NugetFeed.sln /p:Configuration=Release /p:Platform="Any CPU"
    
    - name: Pack Package 
      run: dotnet pack --no-build -c Release NugetFeed/HelloWorld/HelloWorld.csproj -o .
      
    - name: Publish Package
      run: dotnet nuget push *.nupkg -s https://nuget.pkg.github.com/RaviPrasadOrg/index.json -k ${{secrets.NUGET_API_KEY}} --skip-duplicate
      
